# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filetransfer.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66iletransfer.proto\x12\x0c\x66iletransfer\"0\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"0\n\x0c\x46ileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x32\x99\x01\n\x0c\x46ileTransfer\x12\x43\n\x08SendFile\x12\x19.filetransfer.FileRequest\x1a\x1a.filetransfer.FileResponse\"\x00\x12\x44\n\x0bReceiveFile\x12\x19.filetransfer.FileRequest\x1a\x1a.filetransfer.FileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'filetransfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEREQUEST']._serialized_start=36
  _globals['_FILEREQUEST']._serialized_end=84
  _globals['_FILERESPONSE']._serialized_start=86
  _globals['_FILERESPONSE']._serialized_end=134
  _globals['_FILETRANSFER']._serialized_start=137
  _globals['_FILETRANSFER']._serialized_end=290
# @@protoc_insertion_point(module_scope)
